In [ ]:
from datetime import datetime
today = datetime.now().strftime("%Y-%m-%d")
print("Hello, world!")
print(f"Today's date prefix is: {today}")

%load_ext autoreload
%autoreload 2

In [ ]:
from ramlytics_database import DynamoDBClient
from ramlytics_database import DbQuery
from ramlytics_yfinance import yf_search

qry = DbQuery(DynamoDBClient())

In [2]:
positions_df = qry.get_account_positions()
positions_df

        account_id symbol quantity avg_price_paid current_price
0   RAM BRKG -3543    GLD        5          389.1        398.38
1   RAM BRKG -3543    XLK      270        57.6495        194.85
2   RAM ROLL -1969   FSTA       30        52.8983        51.715
3   RAM ROLL -1969    GLD        5        345.476        398.38
4   RAM ROTH -2359   FSTA       10           55.8        51.715
5   RAM ROTH -2359    GLD       50       260.2822        398.38
6   RAM ROTH -2359   HODL       10         22.185         24.34
7   RAM ROTH -2359   IDHQ      200        45.2287        44.045
8   RAM ROTH -2359    IVW       80           37.1        142.15
9   RAM ROTH -2359   LVHI       75          42.77        42.456
10  RAM ROTH -2359    QQQ       75       368.0167         734.8
11  RAM ROTH -2359  RYCEY      100        13.2524         20.01
12  RAM ROTH -2359    VYM       30            138      159.1976
13  RAM ROTH -2359    WMT       10        108.676        107.18
14  RAM ROTH -2359    XLK      140        43.1357        194.85
15  SFM ROLL -8322   FSTA      300        50.9184        51.715
16  SFM ROLL -8322    GLD       30       399.3117        398.38
17  SFM ROLL -8322   IDHQ      500         45.275        44.045
18  SFM ROLL -8322    IVW      170       130.0309        142.15
19  SFM ROLL -8322    JNJ       50            162      272.2113
20  SFM ROLL -8322   LVHI     1000        42.8155        42.456
21  SFM ROLL -8322    QQQ       10         314.56         734.8
22  SFM ROLL -8322  RYCEY       44        10.1245         20.01
23  SFM ROLL -8322    SLV       55        51.3065         59.59
24  SFM ROLL -8322    VYM      300        93.9374      159.1976
25  SFM ROLL -8322    WMT       30            100        107.18
26  SFM ROTH -2236   FSTA       29        53.3669        51.715
27  SFM ROTH -2236    GLD       15       398.9333        398.38
28  SFM ROTH -2236   LVHI       75        42.8104        42.456
29  SFM ROTH -2236    SLV       30        55.0847         59.59
30  SFM ROTH -2236    SPY       17       471.2206        768.93
31  SFM ROTH -2236    VYM       30       138.8993      159.1976

In [3]:
# filter positions for a specific symbol
symbol = "XLK"
positions_df = positions_df[positions_df['symbol'] == symbol]
positions_df

        account_id symbol quantity avg_price_paid current_price
1   RAM BRKG -3543    XLK      270        57.6495        194.85
14  RAM ROTH -2359    XLK      140        43.1357        194.85

In [4]:
qry.get_positions_unique_symbols()

<StringArray>
[  'GLD',   'XLK',  'FSTA',  'HODL',  'IDHQ',   'IVW',  'LVHI',   'QQQ',
 'RYCEY',   'VYM',   'WMT',   'JNJ',   'SLV',   'SPY']
Length: 14, dtype: str

In [5]:
summary_df = qry.summarize_accounts_by_symbol()
# sort summary by total value
summary_df = summary_df.sort_values(by='total_value', ascending=False)
summary_df = summary_df.reset_index(drop=True)
#summary_df.to_csv('summary.csv', index=False)
summary_df

,symbol,total_quantity,avg_price_paid,current_price,accounts,total_value
0,XLK,410,50.3926,194.85,"[RAM ROTH -2359, RAM BRKG -3543]",79888.500
1,QQQ,85,341.28835,734.8,"[SFM ROLL -8322, RAM ROTH -2359]",62458.000
2,VYM,360,123.612233,159.1976,"[SFM ROLL -8322, SFM ROTH -2236, RAM ROTH -2359]",57311.136
3,LVHI,1150,42.798633,42.456,"[SFM ROLL -8322, SFM ROTH -2236, RAM ROTH -2359]",48824.400
4,GLD,105,358.62064,398.38,"[RAM ROLL -1969, RAM ROTH -2359, SFM ROTH -223...",41829.900
5,IVW,250,83.56545,142.15,"[SFM ROLL -8322, RAM ROTH -2359]",35537.500
6,IDHQ,700,45.25185,44.045,"[SFM ROLL -8322, RAM ROTH -2359]",30831.500
7,FSTA,369,53.2459,51.715,"[SFM ROLL -8322, SFM ROTH -2236, RAM ROLL -196...",19082.835
8,JNJ,50,162.0,272.2113,[SFM ROLL -8322],13610.565
9,SPY,17,471.2206,768.93,[SFM ROTH -2236],13071.810
10,SLV,85,53.1956,59.59,"[SFM ROLL -8322, SFM ROTH -2236]",5065.150
11,WMT,40,104.338,107.18,"[SFM ROLL -8322, RAM ROTH -2359]",4287.200
12,RYCEY,144,11.68845,20.01,"[SFM ROLL -8322, RAM ROTH -2359]",2881.440
13,HODL,10,22.185,24.34,[RAM ROTH -2359],243.400

In [6]:
qry.enhance_top10_holdings(symbols=['XLK'])

Symbol: XLK, Pct in Top 10: 55.8

In [9]:
eft_holdings_df = qry.get_instrument_holdings()
eft_holdings_df.to_csv("eft_holdings.csv", index=False)
eft_holdings_df

FSTA
GLD
HODL
IDHQ
IVW
JNJ
LVHI
QQQ
RYCEY
SLV
SPY
VYM
WMT
XLK

,etf_symbol,quoteType,exchDisp,dispSecIndFlag,industryDisp,sectorDisp,score,symbol,index,exchange,...,name,isYahooFinance,industry,typeDisp,current_price,shortname,weight_percent,longname,nameChangeDate,prevName
0,FSTA,EQUITY,NASDAQ,True,Discount Stores,Consumer Defensive,29759000,WMT,quotes,NMS,...,Walmart Inc,True,Discount Stores,Equity,107.18,Walmart Inc.,13.4,Walmart Inc.,NaN,NaN
1,FSTA,EQUITY,NASDAQ,True,Discount Stores,Consumer Defensive,30832000,COST,quotes,NMS,...,Costco Wholesale Corp,True,Discount Stores,Equity,893.46,Costco Wholesale Corporation,11.3,Costco Wholesale Corporation,NaN,NaN
2,FSTA,EQUITY,NYSE,False,Beverages—Non—Alcoholic,Consumer Defensive,20970000,KO,quotes,NYQ,...,Coca-Cola Co,True,Beverages—Non-Alcoholic,Equity,87.925,Coca-Cola Company (The),8.5,The Coca-Cola Company,NaN,NaN
3,FSTA,EQUITY,NYSE,False,Household & Personal Products,Consumer Defensive,16647500,PG,quotes,NYQ,...,Procter & Gamble Co,True,Household & Personal Products,Equity,145.99,Procter & Gamble Company (The),8.4,The Procter & Gamble Company,NaN,NaN
4,FSTA,EQUITY,NYSE,True,Tobacco,Consumer Defensive,14427500,PM,quotes,NYQ,...,Philip Morris International Inc,True,Tobacco,Equity,186.765,Philip Morris International Inc,4.5,Philip Morris International Inc.,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,XLK,EQUITY,NASDAQ,True,Communication Equipment,Technology,21338500,CSCO,quotes,NMS,...,Cisco Systems Inc,True,Communication Equipment,Equity,111.46,"Cisco Systems, Inc.",3.2,"Cisco Systems, Inc.",NaN,NaN
89,XLK,EQUITY,NASDAQ,True,Semiconductors,Technology,208306496,INTC,quotes,NMS,...,Intel Corp,True,Semiconductors,Equity,121.78,Intel Corporation,3,Intel Corporation,NaN,NaN
90,XLK,EQUITY,NASDAQ,True,Semiconductor Equipment & Materials,Technology,32894000,AMAT,quotes,NMS,...,Applied Materials Inc,True,Semiconductor Equipment & Materials,Equity,464.24,"Applied Materials, Inc.",2.8,"Applied Materials, Inc.",NaN,NaN
91,XLK,EQUITY,NASDAQ,True,Semiconductor Equipment & Materials,Technology,25999000,LRCX,quotes,NMS,...,Lam Research Corp,True,Semiconductor Equipment & Materials,Equity,302.28,Lam Research Corporation,2.5,Lam Research Corporation,NaN,NaN
92,XLK,EFT,NaN,NaN,NaN,NaN,NaN,XLK,NaN,NaN,...,holdings outside the top 10,NaN,--,NaN,194.85,NaN,44.2,NaN,NaN,NaN

In [13]:
# create an xlsx file with tabs for ETF holdings and account positions
import pandas as pd

with pd.ExcelWriter("etf_and_account_positions.xlsx") as writer:
    eft_holdings_df.to_excel(writer, sheet_name="ETF Holdings", index=False)
    positions_df = qry.get_account_positions()
    positions_df.to_excel(writer, sheet_name="Account Positions", index=False)
    summary_df = qry.summarize_accounts_by_symbol(positions_df)
    summary_df.to_excel(writer, sheet_name="Account Symbols Summary", index=False)

In [ ]:
if __name__ == "__main__":

In [ ]:
# local test for dyndb_load_json module

import backend.dyndb_load_json.dyndb_load_json as dyndb_load_json

import os
outpath = os.getenv("OUTPATH", "/tmp/accounts") 

import boto3
s3_bucket = os.getenv("S3_BUCKET", "fh-danelfin-289755104220")
s3_ingest_folder = "inbound/"
s3_client = boto3.client("s3")

# for each .json in the s3 bucket under the key prefix
response = s3_client.list_objects_v2(Bucket=s3_bucket, Prefix=s3_ingest_folder)
for obj in response.get("Contents", []):
    key = obj["Key"]

    # process only files in root folder
    if "/" in key[len(s3_ingest_folder):]:
        continue

    if key.endswith(".json") :
        #print(f"Found JSON file: s3://{s3_bucket}/{key}")

        # emulate an s3 ObjectCreated event for the lambda handler
        event = {
            "Records": [
                {
                    "s3": {
                        "bucket": {"name": s3_bucket},
                        "object": {"key": key},
                    }
                }
            ]
        }
        dyndb_load_json.lambda_handler(event, None) # local test

print("Finished processing all JSON files.")

In [ ]:
danelfin_api_key = os.getenv("DANELFIN_API_KEY")

import backend.danelfin.danelfin as danelfin
client = danelfin.DanelfinClient(api_key=danelfin_api_key)

from datetime import datetime

# 1. Historical data for a ticker
pypl_history = client.ranking(ticker="XLK")
pypl_history

In [ ]:
# sync with s3 bucket
import boto3
import os

local_folder = os.getenv("LOCAL_FOLDER", "./downloads/news")
if not os.path.exists(local_folder):
    os.makedirs(local_folder)

s3 = boto3.client("s3")
s3_bucket_name = os.getenv("S3_BUCKET_NAME", "fh-danelfin-289755104220")
s3_folder = os.getenv("S3_FOLDER", "inbound/news")
paginator = s3.get_paginator("list_objects_v2")

# pull/push sync with S3 

# download files from s3 bucket
downloaded_files = set()
for page in paginator.paginate(Bucket=s3_bucket_name, Prefix=s3_folder):
    for obj in page.get("Contents", []):
        key = obj["Key"]
        if key.endswith("/"):
            continue    
        print(key)
        local_path = os.path.join(local_folder, os.path.relpath(key, s3_folder))
        local_dir = os.path.dirname(local_path)
        if not os.path.exists(local_dir):
            os.makedirs(local_dir)
        s3.download_file(s3_bucket_name, key, local_path)
        downloaded_files.add(local_path)

# upload local files to s3 bucket (excluding ones just downloaded)
for root, dirs, files in os.walk(local_folder):
    for filename in files:
        if os.path.join(root, filename) in downloaded_files:
            continue
        local_path = os.path.join(root, filename)
        relative_path = os.path.relpath(local_path, local_folder)
        s3_key = os.path.join(s3_folder, relative_path)
        s3.upload_file(local_path, s3_bucket_name, s3_key)

print("Sync complete.")

In [ ]:
local_path, local_dir, key